In [2]:
import pandas as pd

In [6]:
# DATOS FIFA COMPLETOS
df_fifa_22_total = pd.read_csv("./data/players_22.csv")

C:\Users\Francisco\AppData\Local\Temp\ipykernel_12132\1304751918.py:2: DtypeWarning: Columns (25,108) have mixed types. Specify dtype option on import or set low_memory=False.
  df_fifa_22_total = pd.read_csv("./data/players_22.csv")

In [7]:
# Columnas a quedarnos
columnas_conservar = ["sofifa_id","short_name","long_name","club_position","overall","potential"
                      ,"pace","shooting","attacking_finishing","power_shot_power","power_long_shots","attacking_heading_accuracy","attacking_volleys",
                      "mentality_aggression","skill_fk_accuracy","mentality_penalties","dribbling","physic",
                      "attacking_short_passing","skill_ball_control","movement_acceleration",
                      "movement_sprint_speed","movement_agility","movement_reactions","movement_balance","power_jumping",
                      "power_strength","mentality_positioning","mentality_vision",
                      "preferred_foot","weak_foot","international_reputation",
                      "value_eur","age","height_cm","weight_kg","club_team_id","club_name","league_name","league_level","club_jersey_number",
                      "nationality_id","nationality_name",]

In [8]:
# DATOS FIFA FILTRADOS
df_fifa_filtrado = df_fifa_22_total.filter(items=columnas_conservar)

In [9]:
# DATOS FIF SOLO ESP
df_fifa_esp = df_fifa_filtrado[df_fifa_filtrado["league_name"] == "Spain Primera Division"]
df_fifa_esp

,sofifa_id,short_name,long_name,club_position,overall,potential,pace,shooting,attacking_finishing,power_shot_power,...,age,height_cm,weight_kg,club_team_id,club_name,league_name,league_level,club_jersey_number,nationality_id,nationality_name
5,200389,J. Oblak,Jan Oblak,GK,91,93,NaN,NaN,11,59,...,28,188,87,240.0,Atlético de Madrid,Spain Primera Division,1.0,13.0,44,Slovenia
8,192448,M. ter Stegen,Marc-André ter Stegen,GK,90,92,NaN,NaN,14,66,...,29,187,85,241.0,FC Barcelona,Spain Primera Division,1.0,1.0,21,Germany
11,165153,K. Benzema,Karim Benzema,CF,89,89,76.0,86.0,90,85,...,33,185,81,243.0,Real Madrid CF,Spain Primera Division,1.0,9.0,18,France
12,192119,T. Courtois,Thibaut Courtois,GK,89,91,NaN,NaN,14,56,...,29,199,96,243.0,Real Madrid CF,Spain Primera Division,1.0,1.0,7,Belgium
14,200145,Casemiro,Carlos Henrique Venancio Casimiro,CDM,89,89,65.0,73.0,64,88,...,29,185,84,243.0,Real Madrid CF,Spain Primera Division,1.0,14.0,54,Brazil
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16775,258689,Diego Bri,Diego Vicente Bri Carrazoni,RES,58,74,60.0,55.0,58,59,...,18,172,65,468.0,Elche CF,Spain Primera Division,1.0,29.0,45,Spain
16833,260863,W. Suzuki,Wadi Ibrahim Suzuki,RES,58,75,61.0,55.0,59,51,...,18,192,85,461.0,Valencia CF,Spain Primera Division,1.0,31.0,163,Japan
16965,264097,Alex Rodríguez,Alejandro Rodríguez Lorite,RES,58,72,66.0,26.0,22,26,...,19,178,73,1860.0,Getafe CF,Spain Primera Division,1.0,30.0,45,Spain
16966,264098,A. Akurugu,Amankwaa Akurugu,RES,58,73,63.0,25.0,22,25,...,19,174,70,1860.0,Getafe CF,Spain Primera Division,1.0,34.0,117,Ghana
17629,258688,Lluis Andreu,Lluís Andreu i Ruiz,RES,56,64,NaN,NaN,5,41,...,21,189,77,468.0,Elche CF,Spain Primera Division,1.0,28.0,45,Spain

In [6]:
# SOLO ID Y NOMBRE
cols_solo_nombres = ["sofifa_id","short_name","long_name"]
df_fifa_solo_nombres = df_fifa_esp.filter(items=cols_solo_nombres)

In [9]:
# DATOS REALES
df_reales = pd.read_csv("DatosReales_12_10_2024.csv")

In [12]:
# Eliminar columna unnamed
df_reales.drop(columns=["Unnamed: 0"],inplace=True)

In [16]:
# GOLEADORES REALES (y portería invatida)
df_reales_goleadores = df_reales[df_reales["GOLES_PORTERIA"]>0]

In [18]:
display(df_reales_goleadores,df_fifa_solo_nombres)

,NOMBRE,PJ,PT,GOLES_PORTERIA,ASISTENCIAS,TARJETAS,EQUIPO
0,T. Courtois,36,36,29,0,1,real_madrid
1,Andriy Lunin,2,2,2,0,0,real_madrid
2,Dani Carvajal,24,17,1,3,1,real_madrid
3,Éder Militão,34,34,1,2,5,real_madrid
4,David Alaba,30,30,2,3,2,real_madrid
...,...,...,...,...,...,...,...
498,Manu Vallejo,11,2,1,1,0,deportivo_alavés
499,Luis Rioja,37,36,1,3,3,deportivo_alavés
500,Joselu,37,35,14,4,0,deportivo_alavés
503,M. De La Fuente,22,10,1,1,2,deportivo_alavés
504,Édgar Méndez,32,17,1,2,6,deportivo_alavés

       sofifa_id      short_name                          long_name
5         200389        J. Oblak                          Jan Oblak
8         192448   M. ter Stegen              Marc-André ter Stegen
11        165153      K. Benzema                      Karim Benzema
12        192119     T. Courtois                   Thibaut Courtois
14        200145        Casemiro  Carlos Henrique Venancio Casimiro
...          ...             ...                                ...
16775     258689       Diego Bri        Diego Vicente Bri Carrazoni
16833     260863       W. Suzuki                Wadi Ibrahim Suzuki
16965     264097  Alex Rodríguez         Alejandro Rodríguez Lorite
16966     264098      A. Akurugu                   Amankwaa Akurugu
17629     258688    Lluis Andreu                Lluís Andreu i Ruiz

[633 rows x 3 columns]

In [17]:
df_fifa_solo_nombres.to_csv("df_fifa_solo_nombres1.csv")
df_reales_goleadores.to_csv("df_reales_goleadores1.csv")

In [4]:
df_reales_id = pd.read_csv("./data/goleadores_id.csv").drop(columns=["Unnamed: 0.1","Unnamed: 0"])
df_reales_id

,Match_id,short_name,PJ,PT,GOLES_PORTERIA,ASISTENCIAS,TARJETAS,EQUIPO,best_match
0,264240,Gavi,34,28,2,5,10,barcelona,Gavi
1,263880,J. Agirrezabala,4,4,5,0,0,athletic,Agirrezabala
2,262621,G. Mamardashvili,18,18,20,0,2,valencia,G. Mamardashvili
3,259532,Joan García,2,1,3,0,0,espanyol,Joan García
4,259377,Yéremy Pino,31,21,6,4,2,villarreal,Yeremy Pino
...,...,...,...,...,...,...,...,...,...
200,193794,Asier Villalibre,19,3,2,0,0,athletic,NaN
201,211688,José Gayà,24,22,2,4,7,valencia,NaN
202,247131,Pacha Espino,37,37,2,2,6,cádiz,NaN
203,0,Rubén Alcaraz,14,12,2,0,7,cádiz,NaN
204,228805,A. Raíllo,17,17,2,0,8,mallorca,NaN

In [20]:
df_reales_id.rename(columns={"Match_id":"sofifa_id"},inplace=True)

In [21]:
display(df_fifa_esp,df_reales_id)

,sofifa_id,short_name,long_name,club_position,overall,potential,pace,shooting,attacking_finishing,power_shot_power,...,age,height_cm,weight_kg,club_team_id,club_name,league_name,league_level,club_jersey_number,nationality_id,nationality_name
5,200389,J. Oblak,Jan Oblak,GK,91,93,NaN,NaN,11,59,...,28,188,87,240.0,Atlético de Madrid,Spain Primera Division,1.0,13.0,44,Slovenia
8,192448,M. ter Stegen,Marc-André ter Stegen,GK,90,92,NaN,NaN,14,66,...,29,187,85,241.0,FC Barcelona,Spain Primera Division,1.0,1.0,21,Germany
11,165153,K. Benzema,Karim Benzema,CF,89,89,76.0,86.0,90,85,...,33,185,81,243.0,Real Madrid CF,Spain Primera Division,1.0,9.0,18,France
12,192119,T. Courtois,Thibaut Courtois,GK,89,91,NaN,NaN,14,56,...,29,199,96,243.0,Real Madrid CF,Spain Primera Division,1.0,1.0,7,Belgium
14,200145,Casemiro,Carlos Henrique Venancio Casimiro,CDM,89,89,65.0,73.0,64,88,...,29,185,84,243.0,Real Madrid CF,Spain Primera Division,1.0,14.0,54,Brazil
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16775,258689,Diego Bri,Diego Vicente Bri Carrazoni,RES,58,74,60.0,55.0,58,59,...,18,172,65,468.0,Elche CF,Spain Primera Division,1.0,29.0,45,Spain
16833,260863,W. Suzuki,Wadi Ibrahim Suzuki,RES,58,75,61.0,55.0,59,51,...,18,192,85,461.0,Valencia CF,Spain Primera Division,1.0,31.0,163,Japan
16965,264097,Alex Rodríguez,Alejandro Rodríguez Lorite,RES,58,72,66.0,26.0,22,26,...,19,178,73,1860.0,Getafe CF,Spain Primera Division,1.0,30.0,45,Spain
16966,264098,A. Akurugu,Amankwaa Akurugu,RES,58,73,63.0,25.0,22,25,...,19,174,70,1860.0,Getafe CF,Spain Primera Division,1.0,34.0,117,Ghana
17629,258688,Lluis Andreu,Lluís Andreu i Ruiz,RES,56,64,NaN,NaN,5,41,...,21,189,77,468.0,Elche CF,Spain Primera Division,1.0,28.0,45,Spain

,sofifa_id,short_name,PJ,PT,GOLES_PORTERIA,ASISTENCIAS,TARJETAS,EQUIPO,best_match
0,264240,Gavi,34,28,2,5,10,barcelona,Gavi
1,263880,J. Agirrezabala,4,4,5,0,0,athletic,Agirrezabala
2,262621,G. Mamardashvili,18,18,20,0,2,valencia,G. Mamardashvili
3,259532,Joan García,2,1,3,0,0,espanyol,Joan García
4,259377,Yéremy Pino,31,21,6,4,2,villarreal,Yeremy Pino
...,...,...,...,...,...,...,...,...,...
200,193794,Asier Villalibre,19,3,2,0,0,athletic,NaN
201,211688,José Gayà,24,22,2,4,7,valencia,NaN
202,247131,Pacha Espino,37,37,2,2,6,cádiz,NaN
203,0,Rubén Alcaraz,14,12,2,0,7,cádiz,NaN
204,228805,A. Raíllo,17,17,2,0,8,mallorca,NaN

In [22]:
df_fifa_goles_reales = df_fifa_goles_reales = pd.merge(df_fifa_esp, df_reales_id, on="sofifa_id", how="left")

df_fifa_goles_reales

,sofifa_id,short_name_x,long_name,club_position,overall,potential,pace,shooting,attacking_finishing,power_shot_power,...,nationality_id,nationality_name,short_name_y,PJ,PT,GOLES_PORTERIA,ASISTENCIAS,TARJETAS,EQUIPO,best_match
0,200389,J. Oblak,Jan Oblak,GK,91,93,NaN,NaN,11,59,...,44,Slovenia,Jan Oblak,38.0,38.0,43.0,0.0,1.0,atlético,J. Oblak
1,192448,M. ter Stegen,Marc-André ter Stegen,GK,90,92,NaN,NaN,14,66,...,21,Germany,M. Ter Stegen,35.0,35.0,34.0,0.0,3.0,barcelona,M. ter Stegen
2,165153,K. Benzema,Karim Benzema,CF,89,89,76.0,86.0,90,85,...,18,France,K. Benzema,32.0,31.0,27.0,12.0,0.0,real_madrid,K. Benzema
3,192119,T. Courtois,Thibaut Courtois,GK,89,91,NaN,NaN,14,56,...,7,Belgium,T. Courtois,36.0,36.0,29.0,0.0,1.0,real_madrid,T. Courtois
4,200145,Casemiro,Carlos Henrique Venancio Casimiro,CDM,89,89,65.0,73.0,64,88,...,54,Brazil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
628,258689,Diego Bri,Diego Vicente Bri Carrazoni,RES,58,74,60.0,55.0,58,59,...,45,Spain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
629,260863,W. Suzuki,Wadi Ibrahim Suzuki,RES,58,75,61.0,55.0,59,51,...,163,Japan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
630,264097,Alex Rodríguez,Alejandro Rodríguez Lorite,RES,58,72,66.0,26.0,22,26,...,45,Spain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
631,264098,A. Akurugu,Amankwaa Akurugu,RES,58,73,63.0,25.0,22,25,...,117,Ghana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
632,258688,Lluis Andreu,Lluís Andreu i Ruiz,RES,56,64,NaN,NaN,5,41,...,45,Spain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:

df_fifa_goles_reales = df_fifa_goles_reales.drop(df_fifa_goles_reales[df_fifa_goles_reales["club_position"] == "GK"].index)
df_fifa_goles_reales.sort_values("GOLES_PORTERIA",ascending=False)

,sofifa_id,short_name_x,long_name,club_position,overall,potential,pace,shooting,attacking_finishing,power_shot_power,...,nationality_id,nationality_name,short_name_y,PJ,PT,GOLES_PORTERIA,ASISTENCIAS,TARJETAS,EQUIPO,best_match
251,244316,Luís Maximiano,Luís Manuel Arantes Maximiano,SUB,76,83,NaN,NaN,5,49,...,38,Portugal,Luís Maximiano,35.0,35.0,55.0,0.0,2.0,granada,Luís Maximiano
415,236033,Dani Cárdenas,Daniel Cárdenas Líndez,SUB,72,80,NaN,NaN,5,56,...,45,Spain,Dani Cárdenas,24.0,24.0,46.0,0.0,3.0,levante,Dani Cárdenas
126,204234,Edgar Badia,Edgar Badia Guardiola,SUB,79,80,NaN,NaN,12,57,...,45,Spain,Édgar Badía,24.0,24.0,35.0,0.0,2.0,elche,Edgar Badia
75,199987,J. Cillessen,Jasper Cillessen,SUB,81,81,NaN,NaN,10,59,...,34,Netherlands,Jasper Cillessen,17.0,17.0,29.0,1.0,1.0,valencia,NaN
2,165153,K. Benzema,Karim Benzema,CF,89,89,76.0,86.0,90,85,...,18,France,K. Benzema,32.0,31.0,27.0,12.0,0.0,real_madrid,K. Benzema
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
628,258689,Diego Bri,Diego Vicente Bri Carrazoni,RES,58,74,60.0,55.0,58,59,...,45,Spain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
629,260863,W. Suzuki,Wadi Ibrahim Suzuki,RES,58,75,61.0,55.0,59,51,...,163,Japan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
630,264097,Alex Rodríguez,Alejandro Rodríguez Lorite,RES,58,72,66.0,26.0,22,26,...,45,Spain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
631,264098,A. Akurugu,Amankwaa Akurugu,RES,58,73,63.0,25.0,22,25,...,117,Ghana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
632,258688,Lluis Andreu,Lluís Andreu i Ruiz,RES,56,64,NaN,NaN,5,41,...,45,Spain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
df_fifa_goles_reales[df_fifa_goles_reales["club_position"]=="SUB"]

,sofifa_id,short_name_x,long_name,club_position,overall,potential,pace,shooting,attacking_finishing,power_shot_power,...,nationality_id,nationality_name,short_name_y,PJ,PT,GOLES_PORTERIA,ASISTENCIAS,TARJETAS,EQUIPO,best_match
26,186345,K. Trippier,Kieran Trippier,SUB,84,84,73.0,63.0,54,75,...,14,England,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,207863,Felipe,Felipe Augusto de Almeida Monteiro,SUB,84,84,61.0,41.0,39,46,...,54,Brazil,Felipe,26.0,15.0,2.0,1.0,6.0,atlético,Felipe
35,178750,Sergio Asenjo,Sergio Asenjo Andrés,SUB,83,83,NaN,NaN,14,59,...,45,Spain,S. Asenjo,6.0,6.0,9.0,0.0,1.0,villarreal,NaN
41,214997,Á. Correa,Ángel Martín Correa,SUB,83,86,85.0,83.0,85,83,...,52,Argentina,Ángel Correa,36.0,21.0,12.0,5.0,4.0,atlético,NaN
42,220834,Marco Asensio,Marco Asensio Willemsen,SUB,83,86,82.0,80.0,77,86,...,45,Spain,M. Asensio,31.0,19.0,10.0,0.0,2.0,real_madrid,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,238446,Tachi,Alberto Rodríguez Baró,SUB,67,76,54.0,29.0,26,41,...,45,Spain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
498,252865,Iker Losada,Iker Losada Aragunde,SUB,67,79,69.0,69.0,73,70,...,45,Spain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
511,236914,Álex Martín,José Alejandro Martín Valerón,SUB,66,75,51.0,42.0,35,48,...,45,Spain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
527,228869,Camus,Sergio Camus Perojo,SUB,65,72,72.0,47.0,43,61,...,45,Spain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
582,263880,Agirrezabala,Julen Agirrezabala,SUB,63,77,NaN,NaN,7,47,...,45,Spain,J. Agirrezabala,4.0,4.0,5.0,0.0,0.0,athletic,Agirrezabala